### ISSUE TITLE
A global scheme for passing Entity IDs 

### ISSUE THREAD

**Issue by valorekhov** [xbrlus/AuditData-API#3]
Discuss whether to standardize on a specific query string arg (e.g. gl_periods/entity_id=XXXXX) or a URL prefix (e.g. XXXXX/gl_periods)

Additional discussion around:
-  handling hierarchical entities, and;
-  whether passing multiple Entity IDs is to be supported.

As an additional implementation note: Entity IDs  must be unique to a specific data provider (e.g. an auto-incremented integer, a system-generated GUID), and not easily guessable identifiers (i.e. a FEIN, company name) as an additional measure to complicate mining when authorization for data access is otherwise mis-configured.

**Comment by BaxterDevs** [comment]
I agree with the summary of the request. I recommend further clarifying by removing "auto-increment integer" as an option, and leaving the definition as a source system generated **UID** and not a _GUID_ or _UUID_ which give the impression the identifier persists as the primary key across systems.
